[package]
name = "hw1"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
redis = "0.27"